"""Add model and direction columns

Revision ID: 18480f505099
Revises: da9d83ed78f2
Create Date: 2025-06-02 15:57:52.141072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18480f505099'
down_revision = 'da9d83ed78f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('collected_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('project_name')
        batch_op.drop_column('barcode')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('collected_by',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('model')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
