"""Initial migration

Revision ID: da9d83ed78f2
Revises: 
Create Date: 2025-06-02 15:17:23.253546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9d83ed78f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
